```plantuml
@startmindmap
skinparam nodeMargin 10
skinparam lineArrowsize 2

*[#FFAEB9] Goals
**[#FFDAB9] Diplomat
***[#FFFACD] UPSC Exam
****[#FFFACD] IR Degree
****[#FFFACD] IR Course
****[#FFFACD] University
*****[#FFFACD] Stanford#I-S
******[#FFFACD] Best IR Course
**[#98FB98] Stanford Application
***[#98FB98] High School Diploma
***[#98FB98] Sports
****[#98FB98] FootBall Player(Soccer)
*****[#98FB98] Competitive,Professional
******[#98FB98] FC
******[#98FB98] Academic Training
******[#98FB98] Academy Experience
******[#98FB98] Competitive U28, 19 Clubs
***[#98FB98] Instrumental/Vocal
****[#98FB98] Foreign Language Recognition
****[#98FB98] 4 Years Math+English
****[#DCEEFB] Volunteer Work
****[#DCEEFB] 3.99 - 4 GPA
****[#DCEEFB] 1550 - 1600 SAT Ranking
***[#DCEEFB] Engineer
****[#DCEEFB] Degree
*****[#DCEEFB] AIR 1-100
******[#DCEEFB] J2EE
@endmindmap
```

